# Generated by dumpDCWorkflow.py written by Sebastien Bigaret
# Original workflow id/title: eXtreme_iteration_workflow/eXtreme Iteration Workflow
# Date: 2005/10/22 21:40:31.253 GMT+2
#
# WARNING: this dumps does NOT contain any scripts you might have added to
# the workflow, IT IS YOUR RESPONSABILITY TO MAKE BACKUPS FOR THESE SCRIPTS.
#
# No script detected in this workflow
# 
"""
Programmatically creates a workflow type
"""
__version__ = "$Revision: 1.1.1.1 $"[11:-2]

from Products.CMFCore.WorkflowTool import addWorkflowFactory

from Products.DCWorkflow.DCWorkflow import DCWorkflowDefinition

def setupExtreme_iteration_workflow(wf):
    "..."
    wf.setProperties(title='eXtreme Iteration Workflow')

    for s in ['in-progress', 'new', 'completed', 'invoiced']:
        wf.states.addState(s)
    for t in ['retract', 'accept', 'reactivate', 'invoice', 'complete']:
        wf.transitions.addTransition(t)
    for v in ['action', 'review_history', 'actor', 'comments', 'time']:
        wf.variables.addVariable(v)
    for l in ['reviewer_queue']:
        wf.worklists.addWorklist(l)
    for p in ('Access contents information', 'Modify portal content', 'View', 'List folder contents', 'Add Story Content'):
        wf.addManagedPermission(p)
        

    ## Initial State
    wf.states.setInitialState('new')

    ## States initialization
    sdef = wf.states['in-progress']
    sdef.setProperties(title="""In-progress""",
                       transitions=('complete', 'retract'))
    sdef.setPermission('Access contents information', 0, ['Customer', 'Employee', 'Manager', 'Owner'])
    sdef.setPermission('Modify portal content', 0, ['Manager', 'Owner'])
    sdef.setPermission('View', 0, ['Customer', 'Employee', 'Manager', 'Owner'])
    sdef.setPermission('List folder contents', 0, ['Manager', 'Owner'])
    sdef.setPermission('Add Story Content', 0, ['Manager'])

    sdef = wf.states['new']
    sdef.setProperties(title="""New""",
                       transitions=('accept',))
    sdef.setPermission('Access contents information', 0, ['Customer', 'Employee', 'Manager', 'Owner'])
    sdef.setPermission('Modify portal content', 0, ['Manager', 'Owner'])
    sdef.setPermission('View', 0, ['Customer', 'Employee', 'Manager', 'Owner'])
    sdef.setPermission('List folder contents', 0, ['Customer', 'Employee', 'Manager', 'Owner'])
    sdef.setPermission('Add Story Content', 0, ['Customer', 'Employee', 'Manager'])

    sdef = wf.states['completed']
    sdef.setProperties(title="""Completed""",
                       transitions=('invoice', 'reactivate'))
    sdef.setPermission('Access contents information', 0, ['Customer', 'Employee', 'Manager', 'Owner'])
    sdef.setPermission('Modify portal content', 0, ['Manager', 'Owner'])
    sdef.setPermission('View', 0, ['Customer', 'Employee', 'Manager', 'Owner'])
    sdef.setPermission('List folder contents', 0, ['Manager', 'Owner'])
    sdef.setPermission('Add Story Content', 0, [])

    sdef = wf.states['invoiced']
    sdef.setProperties(title="""Invoiced""",
                       transitions=())
    sdef.setPermission('Access contents information', 0, ['Customer', 'Employee', 'Manager', 'Owner'])
    sdef.setPermission('Modify portal content', 0, ['Owner'])
    sdef.setPermission('View', 0, ['Customer', 'Employee', 'Manager', 'Owner'])
    sdef.setPermission('List folder contents', 0, ['Owner'])
    sdef.setPermission('Add Story Content', 0, [])


    ## Transitions initialization
    tdef = wf.transitions['retract']
    tdef.setProperties(title="""Retract""",
                       new_state_id="""new""",
                       trigger_type=1,
                       script_name="""""",
                       after_script_name="""""",
                       actbox_name="""Retract""",
                       actbox_url="""""",
                       actbox_category="""workflow""",
                       props={'guard_roles': 'Manager'},
                       )

    tdef = wf.transitions['accept']
    tdef.setProperties(title="""start working""",
                       new_state_id="""in-progress""",
                       trigger_type=1,
                       script_name="""""",
                       after_script_name="""""",
                       actbox_name="""Start""",
                       actbox_url="""""",
                       actbox_category="""workflow""",
                       props={'guard_roles': 'Employee; Manager'},
                       )

    tdef = wf.transitions['reactivate']
    tdef.setProperties(title="""Reactivate""",
                       new_state_id="""in-progress""",
                       trigger_type=1,
                       script_name="""""",
                       after_script_name="""""",
                       actbox_name="""Reactivate""",
                       actbox_url="""""",
                       actbox_category="""workflow""",
                       props={'guard_roles': 'Manager'},
                       )

    tdef = wf.transitions['invoice']
    tdef.setProperties(title="""invoice iteration""",
                       new_state_id="""invoiced""",
                       trigger_type=1,
                       script_name="""""",
                       after_script_name="""""",
                       actbox_name="""Invoice""",
                       actbox_url="""""",
                       actbox_category="""workflow""",
                       props={'guard_roles': 'Manager'},
                       )

    tdef = wf.transitions['complete']
    tdef.setProperties(title="""completes content""",
                       new_state_id="""completed""",
                       trigger_type=1,
                       script_name="""""",
                       after_script_name="""""",
                       actbox_name="""Finish""",
                       actbox_url="""""",
                       actbox_category="""workflow""",
                       props={'guard_roles': 'Employee; Manager'},
                       )

    ## State Variable
    wf.variables.setStateVar('review_state')

    ## Variables initialization
    vdef = wf.variables['action']
    vdef.setProperties(description="""The last transition""",
                       default_value="""""",
                       default_expr="""transition/getId|nothing""",
                       for_catalog=0,
                       for_status=1,
                       update_always=1,
                       props=None)

    vdef = wf.variables['review_history']
    vdef.setProperties(description="""Provides access to workflow history""",
                       default_value="""""",
                       default_expr="""state_change/getHistory""",
                       for_catalog=0,
                       for_status=0,
                       update_always=0,
                       props={'guard_permissions': 'Request review; Review portal content'})

    vdef = wf.variables['actor']
    vdef.setProperties(description="""The ID of the user who performed the last transition""",
                       default_value="""""",
                       default_expr="""user/getId""",
                       for_catalog=0,
                       for_status=1,
                       update_always=1,
                       props=None)

    vdef = wf.variables['comments']
    vdef.setProperties(description="""Comments about the last transition""",
                       default_value="""""",
                       default_expr="""python:state_change.kwargs.get('comment', '')""",
                       for_catalog=0,
                       for_status=1,
                       update_always=1,
                       props=None)

    vdef = wf.variables['time']
    vdef.setProperties(description="""Time of the last transition""",
                       default_value="""""",
                       default_expr="""state_change/getDateTime""",
                       for_catalog=0,
                       for_status=1,
                       update_always=1,
                       props=None)

    ## Worklists Initialization
    ldef = wf.worklists['reviewer_queue']
    ldef.setProperties(description="""Reviewer tasks""",
                       actbox_name="""Pending (%(count)d)""",
                       actbox_url="""%(portal_url)s/search?review_state=pending""",
                       actbox_category="""global""",
                       props={'guard_permissions': 'Review portal content', 'var_match_review_state': 'pending'})


def createExtreme_iteration_workflow(id):
    "..."
    ob = DCWorkflowDefinition(id)
    setupExtreme_iteration_workflow(ob)
    return ob

addWorkflowFactory(createExtreme_iteration_workflow,
                   id='eXtreme_iteration_workflow',
                   title='eXtreme Iteration Workflow')
